# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
    - python: 3.5
    - python: 3.6
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install --upgrade pip setuptools
  - pip install pytest==5.4.3 pytest-cov
  - pip install numpy==1.19.0
  - pip install scipy==1.5.0
  - pip install matplotlib==3.2.2 
  - pip install codecov
  - pip install -e .
  - pip install spglib==1.15.1
  
before_script: cd tests

script:
  - py.test -v --cov=./

# after_success:
#   - ./tools/travis-upload-wheel.sh

notifications:
    email: false

after_success:
  - codecov
